services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/notefy
    develop:
      watch:
        - path: .
          action: sync
          target: /code
    container_name: notefy-api
    network_mode: host
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notefy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: notefy-postgres
    network_mode: host

networks:
  notefy-networks:
    driver: bridge
